* Test PDFs on Windows
Make client non-global
Try with current pre-fork
pre-fork multiple children


* Test on Windows USB stick
And test install on MDS/NCPS
* Try to reproduce Windows word search bug.

* Post-release to-do items.
** Fix bug with non-ascii paths to databases on Windows
The current code does seem to work when searching texts, and even when jumping to context from search results, but fails when browsing.  The .idt files are opened without a problem in the preliminary stages of browsing, and the seek_passage subroutine works when jumping from a search result, but not when browsing.  Browsing forward after jump to context is also broken.  A strange bug.

Even if that bug is fixed, it is hard to be confident that the current code is right in all scenarios.  The handling of non-ascii paths may depend on the version of Windows and even on the filesystem.  It seems that paths that can be represented in an 8-bit encoding (so-called ANSI codepage) are done that way; others are UTF-16LE.  Any fix will need lots of testing.

I tried saving and reading the path with no encoding, as raw bytes, but that did not work.

** Compare output to Hipparchia
Make sure we export to XML hidden sources for fragments, as in Accius, Carmina
* Long-term to-do items
** Try to restart diogenes-server if it is killed
** Make settings page shorter and clearer
   roughly a variant of firstrun page, but ensure that it still works outside of elect
** Add compact "Go to chap _, sect _, line _" etc. of this work at bottom of browser page
https://github.com/pjheslin/diogenes/issues/20
(and shift move back/forward buttons to the far left where they won't get covered by Perseus window.
** Fix Wide character warnings when a filter name is in utf8
This is tricky, as some names seem to be latin-1, not utf8.
** Try XML::YAX
Possibly faster and better supported, by same author as XML::DOM::Lite.
** Fix Strawberry Perl to use included libxml.
I think this just requires adding strawberry\c\bin to the PATH, so that it can find libxml2-2__.dll
