* Finish XML output functionality

Implement sub-corpora by allowing a list of author numbers.  In cgi script, flatten this to export any author mentioned.

Check availability of XML::LibXML
Do we need to substitute it?
Substitute libxml with XML::DOM:Lite for portability and test it against phi corpus.
Make XML::LibXML a prereq for Linux packages.

* Test on Windows
And test install on MDS/NCPS

* New website

  Downloads
  FAQs
  About
  Feedback
  Help
  Source Code


  Put under d/
  Splash page at /
  add diogenes-help.html as FAQs
  Add contributions / thanks prominently to diogenes

  Fix links from app under help and support
Αdd favicon to website

* Post-release
** Fix all XML validation errors
** Adapt latex output code to enhance XML; extend schema

* Long-term, aspirational to-do items
** Clean-up various Perl warnings.
** Try to restart diogenes-server if it is killed
** Implement print menu item
** Make settings page shorter and clearer
   roughly a variant of firstrun page, but ensure that it still works outside of electron
