* Current

fix handing div algorithm

Add coptic xml output

don't move <head>s to start of div ...

Merge subsequent <hi> elements when attribs identical.  Also when nested.
If you have a seg without rend which only contains a hi, merge its rend

check how it words with ddp, etc.

* Finish XML output functionality

Implement sub-corpora by allowing a list of author numbers.  In cgi script, flatten this to export any author mentioned.

* Write up notes on XML output
** Markup is for layout rather than semantic (with a couple of exceptions)
** Structure is line-based, for both poetry and prose
*** We have to guess.  Sometimes wrongly.  Explain heuristic




* Generate patch for XML::DOM::Lite


* Save file
https://stackoverflow.com/questions/40501424/save-loaded-html-file-from-electron-app
let file = new File([document.documentElement.outerHTML]
           , "file-" + new Date().getTime() + ".html"
           , {type:"text/html", lastModified:new Date().getTime()});

// your content is into a variable named 'content'
var fs = require('fs');
try { fs.writeFileSync('myfile.txt', content, 'utf-8'); }
catch(e) { alert('Failed to save the file !'); }

* Fix HTTP Header overflow
With large number of inflected forms, REQUEST_URI_TOO_LARGE.
Try switching to POST.

* Test on Windows USB stick
And test install on MDS/NCPS

* Post-release
** Adapt latex output code to enhance XML
** Look through Beta Code Manual and add more Unicode

* Long-term, aspirational to-do items
** Clean-up various Perl warnings.
** Try to restart diogenes-server if it is killed
** Implement print menu item
** Make settings page shorter and clearer
   roughly a variant of firstrun page, but ensure that it still works outside of electron
