* Current

Remove if (0) and put that section after else.

don't move <head>s to start of div ...

Check scholia

* Finish XML output functionality

Implement sub-corpora by allowing a list of author numbers.  In cgi script, flatten this to export any author mentioned.

Check out XML::Tidy for indentation at the end.

Go through beta code manual and pick up all unicode equivs.

* Generate patch for XML::DOM::Lite


* Save file
https://stackoverflow.com/questions/40501424/save-loaded-html-file-from-electron-app
let file = new File([document.documentElement.outerHTML]
           , "file-" + new Date().getTime() + ".html"
           , {type:"text/html", lastModified:new Date().getTime()});

// your content is into a variable named 'content'
var fs = require('fs');
try { fs.writeFileSync('myfile.txt', content, 'utf-8'); }
catch(e) { alert('Failed to save the file !'); }

* Fix HTTP Header overflow
With large number of inflected forms, REQUEST_URI_TOO_LARGE.
Try switching to POST.

* Test on Windows USB stick
And test install on MDS/NCPS

* Post-release
** Adapt latex output code to enhance XML
** Look through Beta Code Manual and add more Unicode

* Long-term, aspirational to-do items
** Clean-up various Perl warnings.
** Try to restart diogenes-server if it is killed
** Implement print menu item
** Make settings page shorter and clearer
   roughly a variant of firstrun page, but ensure that it still works outside of electron
