* Bugs
Pigman: When I search for John [1–8]:16, I am taken to the correct verse,  but when I search for [9–16]:16, I am taken to 21:16 (I stopped trying at chap
. 14).
* For next version
** Fix short defs by using Helma's data.
** Keystrokes:
add a keystroke to clear all form elements.  I could also add keystrokes to go to the top/bottom of a long page of search results.
** Check this:
The shortcuts used to navigate do not work on PC, Windows 10 (version 1909).
I suggest also that "move back" and "move forward" (at the bottom of a page) could also be found at the top of a page when you want to navigate in contex
t.
** Have jump-to field at bottom of page that defaults to current passage
** Have Back button show home page in last state.
** Fix TLL PDF download under Windows
Fix Unicode path problem by renaming to TLL01.pdf etc., but continue to permit old names.
** Bug: L-S quies jumping to Nepos Att.
** Add citation info from authtab.xml to exported XML files.
** Update TLL
We are pleased to announce that the TLL Open Access now includes headwords from N (n to neate) and R (r to refobeo), excluding only material published in
 the most recent three years. New material will be added annually to maintain this three-year window in accordance with our agreement with de Gruyter.

* Post-release to-do items.
** Add advanced settings menu item to run Settings.cgi
** Fix Wide character warnings when a filter name is in utf8
This is tricky, as some names seem to be latin-1, not utf8.
** Zoom in/out does not work on Linux and Windows
** Implement server for Unix/Mac that preforks multiple children.
Preforking for speed; multiple children to permit keepalive connections.
** Fix bug with non-ascii paths to databases on Windows
The current code does seem to work when searching texts, and even when jumping to context from search results, but fails when browsing.  The .idt files are opened without a problem in the preliminary stages of browsing, and the seek_passage subroutine works when jumping from a search result, but not when browsing.  Browsing forward after jump to context is also broken.  A strange bug.
** Compare output to Hipparchia
Make sure we export to XML hidden sources for fragments, as in Accius, Carmina
** See about enabling user to configure the font.
* Long-term to-do items
** Make search output paged?
** Make settings page shorter and clearer
   roughly a variant of firstrun page, but ensure that it still works outside of elect
** Add compact "Go to chap _, sect _, line _" etc. of this work at bottom of browser page
https://github.com/pjheslin/diogenes/issues/20
(and shift move back/forward buttons to the far left where they won't get covered by Perseus window.
** Try XML::YAX
Possibly faster and better supported, by same author as XML::DOM::Lite.
** Fix Strawberry Perl to use included libxml.
I think this just requires adding strawberry\c\bin to the PATH, so that it can find libxml2-2__.dll
** Possibly refactor application to only parse prefs file once
We should avoid re-parsing prefs file at each query.
