Merge new branch and make new one

* Bugs
** Pindar bug:
I’m wondering whether you’d consider modifying the click to dictionary command so that it ignores the apostrophes used in Pindar (and elsewhere?) to indicate that mute+liquid are to be taken separately (e.g. γˈλώσσας, O. 6.12).
** Bug:
L-S quies jumping to Nepos Att.
** Accented filter names
try again to fix this.

* For forthcoming version
** Go through github issues
** Fix use of recent TLL fasicles
See how badly this slows down seeking.
** Replace icon for newer Macs.
** Add advanced settings menu item to run the equivalent of Settings.cgi

* For forthcoming release
** Add FAQ about re-centering lost window
** Add info about diagnosing errors by running it from the terminal
** Add new download for Mac silicon
** Add tgz download target for manual installation
*** Give better instructions on website for manual install
Give config file location(s) and syntax for setting database locations 
** Change prebuilt-data repo to use git-lfs (and my ssh key)
** Test "New Window (reset position)" menu item on Windows
Try with a Windows laptop and an external monitor
** See if Zoom in/out now works on Linux and Windows
** Further test TLL download under Windows.
Maybe fix Unicode path problem by renaming to TLL01.pdf etc., but continue to permit old names.
** Check this:
The shortcuts used to navigate do not work on PC, Windows 10 (version 1909).
** Check bug with non-ascii paths to databases on Windows
The current code does seem to work when searching texts, and even when jumping to context from search results, but fails when browsing.  The .idt files are opened without a problem in the preliminary stages of browsing, and the seek_passage subroutine works when jumping from a search result, but not when browsing.  Browsing forward after jump to context is also broken.  A strange bug.

* Near-term to-do items
** Fix short defs by using Helma's data.
** Add dark mode option.
** Add citation info from authtab.xml to exported XML files.
** Import font_fixes from xml-export into desktop display

* Long-term to-do items
** Fix ordering of lemmatized search output
At present, we seem to look for each inflected form in each work separately, which means that the order appears random: one form late in the work is output before another form which comes early in the work.
** Record criteria for complex filters to permit them to be recreated and modified.
** Try XML::YAX
Possibly faster and better supported, by same author as XML::DOM::Lite.
** Fix Strawberry Perl to use included libxml.
I think this just requires adding strawberry\c\bin to the PATH, so that it can find libxml2-2__.dll
** Possibly refactor application to only parse prefs file once
We should avoid re-parsing prefs file at each query.
** Add better interface to Suda, Etym. Magnum, et al.
Provide a way to search them by headword
** Improve epub output
Write dedicated xml to html-for-epub converter.
** Compare output to Hipparchia
Make sure we export to XML hidden sources for fragments, as in Accius, Carmina
