* Current

Fix no solution: tlg1386016.xml

Add provision to specify prose or verse.
For poetic writers, all works titled fragment should be verse.
Option to print name of work before conversion.
Unify both export scripts.
Test libxml's relaxng validation
restart perl server when it crashes
don't move <head>s to start of div ...
then test "no solution" case

for prose, think about starting a new <p> whenever there is a <space> at the very start of a line.

Remove if (0) and put that section after else.

Check scholia

* Finish XML output functionality

Implement sub-corpora by allowing a list of author numbers.  In cgi script, flatten this to export any author mentioned.

Check out XML::Tidy for indentation at the end.

Go through beta code manual and pick up all unicode equivs.

* Generate patch for XML::DOM::Lite

* Test on Windows USB stick
And test install on MDS/NCPS

* Post-release
** Adapt latex output code to enhance XML
** Look through Beta Code Manual and add more Unicode

* Long-term, aspirational to-do items
** Clean-up various Perl warnings.
** Try to restart diogenes-server if it is killed
** Implement print menu item
** Make settings page shorter and clearer
   roughly a variant of firstrun page, but ensure that it still works outside of electron
