* Current

* Make sure all output validates
* Make sure no diff between libxml and lite

** Add coptic xml output

* Improve unconverted Greek detection and fix runs of Greek in Aulus Gellius.


** Integrate XML output in application
In cgi script, flatten custom corpus to export any author mentioned.



* Generate patch for XML::DOM::Lite


* Save file
https://stackoverflow.com/questions/40501424/save-loaded-html-file-from-electron-app
let file = new File([document.documentElement.outerHTML]
           , "file-" + new Date().getTime() + ".html"
           , {type:"text/html", lastModified:new Date().getTime()});

// your content is into a variable named 'content'
var fs = require('fs');
try { fs.writeFileSync('myfile.txt', content, 'utf-8'); }
catch(e) { alert('Failed to save the file !'); }

* Fix HTTP Header overflow
With large number of inflected forms, REQUEST_URI_TOO_LARGE.
Try switching to POST.

* Test on Windows USB stick
And test install on MDS/NCPS


* Catch browser seeking beyond end of work, signalled by f0fe.

* Long-term to-do items
** Try to restart diogenes-server if it is killed
** Implement print menu item
** Make settings page shorter and clearer
   roughly a variant of firstrun page, but ensure that it still works outside of elect
** Add compact "Go to chap _, sect _, line _" etc. of this work at bottom of browser page
https://github.com/pjheslin/diogenes/issues/20
(and shift move back/forward buttons to the far left where they won't get covered by Perseus window.
