* Current

** don't move <head>s to start of div
And other pending changes to post-processing
Figure out why removing n="t" divs has stopped working

** Post-processing: Merge elements
*** Merge identical elements with identical attribs when adjacent or only whitespace nodes intervene. 
*** When an element has only one non-blank child, and the child is a <hi> element, move the rend attrib to the parent (check for duplicates) and delete the child (promoting its children).
*** If a <hi> element has a parent which includes the same rend attrib, delete the element (and promote its children).

** check how export words with ddp, etc.
** Add coptic xml output

** Integrate XML output in application
In cgi script, flatten custom corpus to export any author mentioned.

* Write up notes on XML output
** Markup is for layout rather than semantic (with a couple of exceptions)
** Structure is line-based, for both poetry and prose
*** We have to guess.  Sometimes wrongly.  Explain heuristic




* Generate patch for XML::DOM::Lite


* Save file
https://stackoverflow.com/questions/40501424/save-loaded-html-file-from-electron-app
let file = new File([document.documentElement.outerHTML]
           , "file-" + new Date().getTime() + ".html"
           , {type:"text/html", lastModified:new Date().getTime()});

// your content is into a variable named 'content'
var fs = require('fs');
try { fs.writeFileSync('myfile.txt', content, 'utf-8'); }
catch(e) { alert('Failed to save the file !'); }

* Fix HTTP Header overflow
With large number of inflected forms, REQUEST_URI_TOO_LARGE.
Try switching to POST.

* Test on Windows USB stick
And test install on MDS/NCPS


* Long-term to-do items
** Try to restart diogenes-server if it is killed
** Implement print menu item
** Make settings page shorter and clearer
   roughly a variant of firstrun page, but ensure that it still works outside of elect
** Add compact "Go to chap _, sect _, line _" etc. of this work at bottom of browser page
https://github.com/pjheslin/diogenes/issues/20
(and shift move back/forward buttons to the far left where they won't get covered by Perseus window.
