#!/usr/bin/env perl

use strict;
use warnings;

use XML::LibXML;
binmode(STDOUT, ':utf8');

# output from phi2tei is input to us
my $indir = 'output';
opendir( my $dh, $indir ) or die "Could not open $indir\n";

my $outdir = 'tess';
use File::Path qw(remove_tree);
if (-e $outdir) {
    remove_tree($outdir);
}
mkdir $outdir;
chdir $outdir;

my ($author, $work);

for my $file (readdir $dh) {
#      next unless $file =~ m/0448001/;
#        next unless $file =~ m/1020/;
    next if $file =~ m/^\./;
    next if $file =~ m/authtab/;
    next if $file =~ m/tmp/;
    next if $file =~ m/9999001/;
    print "Processing $file\n";
    process_file("../$indir/$file");
}
closedir $dh;

my (%div);
    
sub process_file {
    my $file = shift;

    my $parser = XML::LibXML->new();
    my $xmldoc = $parser->parse_file($file);

    $author =
        $xmldoc->getElementsByTagName('author')->[0]->textContent;
    if ($author) {
        print "$author\n";
    }
    else {
        die "No author for $file";
    }
    $author =~ s/\s+/_/g;
    $author =~ s/\.//g;
    $work = $xmldoc->getElementsByTagName('title')->[0]->textContent;
    if ($work) {
        print "  $work ($file)\n";
#         return;
    }
    else {
        die "No work for $file";
    }
    $work =~ s/\s+/_/g;

    my $outfile = "$author.$work.tess";
    open(OUT_FH, ">:utf8", $outfile)
        or die "cannot open $outfile: $!";
    
    foreach my $node ($xmldoc->getElementsByTagName('body')) {
        process_node($node);
    }

    close OUT_FH or die $!;

        
}

my @levels;

my ($state, $line);
sub process_node {
    my $node = shift;
    my $name = $node->nodeName;
    #     print "$name\n";
    if ($name eq 'div') {
        my $n = $node->getAttribute('n');
        my $t = $node->getAttribute('type');
        return if $t eq 'explicit'; # Weirdness in Porphyry on Horace
        $div{$t} = $n;
        push @levels, $t;
        $state = 1;
        #          print "Foo $t $n \n";
#         print join ':', @levels, "\n";
    }
    elsif ($name eq 'l') {
        $line = $node->getAttribute('n');
        $state = 1;        
    }
    elsif ($name eq 'head') {
        return;
    }

    # Text content
    if ($node->nodeValue) {
        if ($state) {
#             print join ',', @levels;
            my $out = "\n<$author.$work ";
            foreach my $level ( @levels ) {
                $out .= $div{$level}.".";
            }
            if ($line) {
                $out .= $line
            }
            else {
                chop $out;
            }
            $out .= "> ";
            print OUT_FH "$out";
            $state = 0;
            $line = '';
        }
        my $text = $node->nodeValue;
        $text =~ s/\s*\n\s*/ /g;
        print OUT_FH $text;
    }
    foreach my $child ($node->nonBlankChildNodes) {
        process_node($child);
    }
    if ($name eq 'div') {
        pop @levels;
    }
}


