#!/usr/bin/env -S perl -w
use strict;

print "# This is auto-generated by make_unicode_compounds.pl.  Do not edit.\n\n";
print "%Diogenes::UnicodeInput::unicode_equivs = (\n";

my @case;
while (<>) {
    my @f = split ";";
    next unless $f[1] =~ m/^GREEK|COPTIC/;
    next unless $f[1] =~ m/LETTER/;
    next if $f[5] =~ m/<sub>|<super>/;

    if ($f[1] =~ m/CAPITAL/) {
        if ($f[13] =~ m/([0-9A-F]+)/) {
            push @case, q("\x{).$f[0].q(}" => "\x{).$1.q(}", )."\n";
        }
    }

    next if $f[5] eq '';
    if ($f[5] =~ m/^([0-9A-F]+)$/) {
        print q("\x{).$f[0].q(}" => "\x{).$1.q(}", )."\n";
        next;
    }
    elsif ($f[5] =~ m/^([0-9A-F]+) ([0-9A-F]+)$/) {
        print q("\x{).$f[0].q(}" => ["\x{).$1.q(}", "\x{).$2.q(}"], )."\n";
    }
    else {
        die "What is ->$f[5]<- ($f[0])?";
    }
}

print ");

";

print "%Diogenes::UnicodeInput::upper_to_lower = (\n";
print $_ for @case;
print ");

1;
";
